version: '3.8'

services:
  api:
    build:
      context: ./DotnetAPI
      dockerfile: Dockerfile
    container_name: teddymo_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - webnet

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     # - ./apiteddymo:/var/www/api
  #     - ./fteddymo/dist:/var/www/frontend:ro
  #     - ./dteddymo/dist:/var/www/dashboard:ro
  #     - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - api
  #   networks:
  #     - webnet


networks:
  webnet:
    external: true
