version: "3.8"

services:
  # Laravel API (PHP + Nginx + MySQL)
  apiteddymo:
    build: ./apiteddymo
    container_name: apiteddymo
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_KEY: base64:somekeyhere
      APP_DEBUG: 'false'
      APP_URL: https://connect.teddy.co.za
    volumes:
      - ./apiteddymo:/var/www
    networks:
      - webnet

  # Static frontend for teddy.co.za
  # fteddymo:
  #   image: nginx:alpine
  #   container_name: fteddymo
  #   volumes:
  #     - ./fteddymo/dist:/usr/share/nginx/html:ro
  #   networks:
  #     - webnet

  # Static frontend for deshboard.teddy.co.za
  # dteddymo:
  #   image: nginx:alpine
  #   container_name: dteddymo
  #   volumes:
  #     - ./dteddymo/dist:/usr/share/nginx/html:ro
  #   networks:
  #     - webnet

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dteddymo/dist:/usr/share/nginx/html/dteddymo:ro
      - ./fteddymo/dist:/usr/share/nginx/html/fteddymo:ro
    depends_on:
      - apiteddymo
      - fteddymo
      - dteddymo
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
