version: '3.8'

services:
  # app:
  #   build:
  #     context: ./apiteddymo
  #     dockerfile: Dockerfile
  #   image: laravel-app
  #   container_name: laravel-app
  #   # restart: unless-stopped
  #   volumes:
  #     - ./apiteddymo:/var/www/api
  #   networks:
  #     - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    # restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CORS_ALLOWED_ORIGINS=http://localhost,http://deshboard.localhost
    ports:
      - "80:80"
    volumes:
      # - ./apiteddymo:/var/www/api
      - ./fteddymo/dist:/var/www/frontend:ro
      - ./dteddymo/dist:/var/www/dashboard:ro
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - app
    networks:
      - laravel

networks:
  laravel:
